language: objective-c
before_install:
  - sudo easy_install cpp-coveralls
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - pod install
script:
  - ./script/run-test.sh | xcpretty
after_success:
  - coveralls -e Pods -e ZSTToolkitTests
